### ISSUE TITLE
Updates to JSON-RPC 2.0 Schemas

### ISSUE THREAD

**Issue by mpcm** [fge/sample-json-schemas#1]
Hi, these items need addressing in the schemas:

Request: This needs to be either a single instance of the current definition, or an unbound array of such objects (batch). Other than that I think it looks good.

Response: Result can be any type, not just an object. Same thing about batch, and needing to be an instance or an array of instances.

Handling in general should be to use the confirm the object shape, but not exclude any additional data fields.

**Comment by fge** [comment]
OK, fixing it. Is the `method` object in a request really optional?

**Comment by fge** [comment]
I have updated both and tested with the data I could find, so far so good. Do you see any other constraints which would have escaped my attention?

**Comment by mpcm** [comment]
Method in a request object should be required.
